# test指令中猪多少tick(s)传送到玩家身边
period: 0
# 至少需要多少名玩家才能开始游戏(不写为默认2)
min-player-count: 2

# 开始游戏后，会留对应的tick让玩家保存自己背包里的贵重物品（默认200）
delay-tick: 200
# 开始游戏时，将所有玩家传送到当前世界的某一坐标，可以设置为竞技场的坐标之类的
start-x: 0
start-y: 0
start-z: 0

# 游戏结束后将所有玩家传送到的坐标，可以设置为主城之类的
end-x: 0
end-y: 0
end-z: 0