# test指令中猪多少tick(s)传送到玩家身边
period: 0

# 至少需要多少名玩家才能开始游戏(不写为默认4)
min-player-count: 4

# 开始游戏后，会留对应的tick让玩家保存自己背包里的贵重物品（默认200）
delay-tick: 200

# 开始游戏时，将所有玩家传送到当前世界的某一个坐标，可以设置为竞技场的坐标之类的
start-tp: false
start-x: 0
start-y: 0
start-z: 0

# 游戏结束后将所有玩家传送到的坐标，可以设置为主城之类的
end-x: 0
end-y: 0
end-z: 0

# 资源刷新点，会不断在设定地点生成对应的凋落物
resources:
  firework-rocket:  # 烟花火箭
    - x: 0 # 资源点的坐标
      y: 0
      z: 0
      amount: 5  # 每次刷新的数量
    - x: 70
      y: 70
      z: 70
      amount: 5

  arrow:  # 箭
    - x: 10
      y: 0
      z: 10
      amount: 5
    - x: 80
      y: 70
      z: 80
      amount: 5

  golden_apple:  # 金苹果
    - x: 20
      y: 0
      z: 20
      amount: 5
    - x: 90
      y: 70
      z: 90
      amount: 5

# 刷新资源间隔ticks
refresh-tick: 20